server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql_address:3306/hcbm_platform?useUnicode=true&characterEncoding=utf-8
    username: hcbm
    password: hcbm
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml