server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql_host:3306/hcbm_platform?useUnicode=true&characterEncoding=utf-8
    username: hcbm
    password: hcbm
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://10.211.55.29:2181
  scan:
    base-packages: com.hand.userservice.*
  protocol:
    name: dubbo
    port: 20881
    host: 10.211.55.29