server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://10.211.55.29:3306/hcbm_platform?useUnicode=true&characterEncoding=utf-8
    username: hcbm
    password: hcbm

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml