server:
  port: 8080
spring:
  application:
    name: elasticsearch
dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://zookeeper_host:2181
  scan:
    base-packages: com.hand.userservice
  protocol:
    name: dubbo
    port: 20880