server:
  port: 8080
spring:
  application:
    name: elasticsearch
dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://10.211.55.29:2181
  scan:
    base-packages: com.hand.elasticsearch.controller
  protocol:
    name: dubbo
    port: -1